# The random and string modules are imported at the beginning of the code.
import random
import string
# The string.printable variable is assigned the value of a string containing all printable ASCII characters, including digits, letters, punctuation marks, and whitespace.
printable = string.printable

#  An empty list password_result is created to store the characters generated by the password generation function.
password_result = []


# The password() function is defined with no parameters.
def password():
# The function loops through a range of 1 to 9 (inclusive) to generate 8 random characters, using the random.choice() method to select a random character from the printable string, and append it to the password_result list.
    for ch in range(1, 9):
        ch = random.choice(printable)
        password_result.append(ch)
# The password() function returns the password_result list as a tuple.
    return tuple(password_result)


# The result variable is assigned the value of the password() function call, which generates a random password.
result = password()
print('Your password: ', end='')
for ch in result:
    print(ch, end='')
# The generated password is printed to the console as a single string of 8 random characters.

